package com.tweetapp.model;

import java.time.LocalDateTime;

import java.util.List;

import javax.validation.constraints.NotNull;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
@Data
@NoArgsConstructor
//@Document(collection = "tweets")
@DynamoDBTable(tableName = "Tweet")
public class Tweet {
	
	//@Id
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String tweetName;
	//@CreatedDate
	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute
	private String postDate;
	@DynamoDBAttribute
	private long likes;
	@DynamoDBAttribute
	private User user;
	@DynamoDBAttribute
	private List<Tweet> replies;
	@DynamoDBAttribute
	private String tweetTag;
	


}
